server:
  port: 8080
  servlet:
    context-path: /webchatMgr


spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid????
        druid:
          #???????filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #????
          url: jdbc:mysql://127.0.0.1:3306/netty?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: 123456
          #???????/??/??
          initial-size: 1
          min-idle: 1
          max-active: 20
          #??????????
          max-wait: 60000
          #??????????????????????
          time-between-eviction-runs-millis: 60000
          #??????????????
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #??PSCache?????????PSCache????oracle??true?mysql??false????????????false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
#    mvc:
#        view:
#          prefix: /WEB-INF/views/
#          suffix: .jsp
#        jackson:
#            date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hexin.webchat.entity



#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check